/**
 * PULSAR-X: Cinematic Domain - Audio Subsystem
 * AudioProfiles: Scene-Aware Audio Configurations for all 18 Narrative Scenes.
 */

import type { SceneAudioProfile } from "./audioTypes";

export const SCENE_AUDIO_PROFILES: readonly SceneAudioProfile[] = [
  {
    sceneId: 1,
    sceneKey: "SCENE_01_EARTH",
    ambienceGain: 0.30,
    spacecraftGain: 0.50,
    pulsarGain: 0.0,
    telemetryGain: 0.40,
    alertGain: 0.0,
    cinematicGain: 0.0,
    activeSources: ["DeepSpaceAmbience", "AvionicsHum"],
    fadeInDuration_s: 0.5,
    fadeOutDuration_s: 0.5,
  },
  {
    sceneId: 2,
    sceneKey: "SCENE_02_DEPARTURE",
    ambienceGain: 0.40,
    spacecraftGain: 0.85,
    pulsarGain: 0.0,
    telemetryGain: 0.30,
    alertGain: 0.0,
    cinematicGain: 0.25,
    activeSources: ["DeepSpaceAmbience", "MainEngineBurn", "AvionicsHum"],
    fadeInDuration_s: 0.8,
    fadeOutDuration_s: 0.8,
  },
  {
    sceneId: 3,
    sceneKey: "SCENE_03_EARTH_RECEDES",
    ambienceGain: 0.45,
    spacecraftGain: 0.40,
    pulsarGain: 0.0,
    telemetryGain: 0.30,
    alertGain: 0.0,
    cinematicGain: 0.15,
    activeSources: ["DeepSpaceAmbience", "AvionicsHum"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 4,
    sceneKey: "SCENE_04_DEEP_SPACE",
    ambienceGain: 0.60,
    spacecraftGain: 0.35,
    pulsarGain: 0.0,
    telemetryGain: 0.25,
    alertGain: 0.0,
    cinematicGain: 0.10,
    activeSources: ["DeepSpaceAmbience"],
    fadeInDuration_s: 0.8,
    fadeOutDuration_s: 0.8,
  },
  {
    sceneId: 5,
    sceneKey: "SCENE_05_GPS_LOST",
    ambienceGain: 0.45,
    spacecraftGain: 0.30,
    pulsarGain: 0.0,
    telemetryGain: 0.20,
    alertGain: 0.80,
    cinematicGain: 0.30,
    activeSources: ["DeepSpaceAmbience", "AlertTone"],
    fadeInDuration_s: 0.3,
    fadeOutDuration_s: 0.5,
  },
  {
    sceneId: 6,
    sceneKey: "SCENE_06_GROUND_LINK_LOST",
    ambienceGain: 0.65,
    spacecraftGain: 0.25,
    pulsarGain: 0.0,
    telemetryGain: 0.15,
    alertGain: 0.60,
    cinematicGain: 0.20,
    activeSources: ["DeepSpaceAmbience"],
    fadeInDuration_s: 0.5,
    fadeOutDuration_s: 0.5,
  },
  {
    sceneId: 7,
    sceneKey: "SCENE_07_SEARCH",
    ambienceGain: 0.50,
    spacecraftGain: 0.30,
    pulsarGain: 0.20,
    telemetryGain: 0.30,
    alertGain: 0.0,
    cinematicGain: 0.20,
    activeSources: ["DeepSpaceAmbience", "AvionicsHum"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 8,
    sceneKey: "SCENE_08_FIRST_PULSAR",
    ambienceGain: 0.40,
    spacecraftGain: 0.30,
    pulsarGain: 0.75,
    telemetryGain: 0.40,
    alertGain: 0.0,
    cinematicGain: 0.60,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification"],
    fadeInDuration_s: 0.8,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 9,
    sceneKey: "SCENE_09_PULSAR_NETWORK",
    ambienceGain: 0.40,
    spacecraftGain: 0.30,
    pulsarGain: 0.70,
    telemetryGain: 0.45,
    alertGain: 0.0,
    cinematicGain: 0.40,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 10,
    sceneKey: "SCENE_10_OBSERVATION",
    ambienceGain: 0.35,
    spacecraftGain: 0.30,
    pulsarGain: 0.65,
    telemetryGain: 0.65,
    alertGain: 0.0,
    cinematicGain: 0.35,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification", "PhotonClicks"],
    fadeInDuration_s: 0.5,
    fadeOutDuration_s: 0.5,
  },
  {
    sceneId: 11,
    sceneKey: "SCENE_11_UNCERTAINTY",
    ambienceGain: 0.55,
    spacecraftGain: 0.30,
    pulsarGain: 0.45,
    telemetryGain: 0.50,
    alertGain: 0.20,
    cinematicGain: 0.30,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 12,
    sceneKey: "SCENE_12_CONVERGENCE",
    ambienceGain: 0.35,
    spacecraftGain: 0.30,
    pulsarGain: 0.60,
    telemetryGain: 0.70,
    alertGain: 0.0,
    cinematicGain: 0.50,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification", "NavigationCompute"],
    fadeInDuration_s: 0.7,
    fadeOutDuration_s: 0.5,
  },
  {
    sceneId: 13,
    sceneKey: "SCENE_13_POSITION_LOCK",
    ambienceGain: 0.30,
    spacecraftGain: 0.30,
    pulsarGain: 0.50,
    telemetryGain: 0.40,
    alertGain: 0.0,
    cinematicGain: 0.75,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification", "NavigationLockTone"],
    fadeInDuration_s: 0.5,
    fadeOutDuration_s: 0.8,
  },
  {
    sceneId: 14,
    sceneKey: "SCENE_14_SIGNAL_FAILURE",
    ambienceGain: 0.45,
    spacecraftGain: 0.30,
    pulsarGain: 0.20,
    telemetryGain: 0.30,
    alertGain: 0.85,
    cinematicGain: 0.40,
    activeSources: ["DeepSpaceAmbience", "SolarInterference"],
    fadeInDuration_s: 0.3,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 15,
    sceneKey: "SCENE_15_DEGRADATION",
    ambienceGain: 0.60,
    spacecraftGain: 0.30,
    pulsarGain: 0.30,
    telemetryGain: 0.35,
    alertGain: 0.55,
    cinematicGain: 0.25,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 16,
    sceneKey: "SCENE_16_RECOVERY",
    ambienceGain: 0.35,
    spacecraftGain: 0.30,
    pulsarGain: 0.65,
    telemetryGain: 0.55,
    alertGain: 0.0,
    cinematicGain: 0.70,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification", "NavigationLockTone"],
    fadeInDuration_s: 0.6,
    fadeOutDuration_s: 0.6,
  },
  {
    sceneId: 17,
    sceneKey: "SCENE_17_DESTINATION",
    ambienceGain: 0.40,
    spacecraftGain: 0.35,
    pulsarGain: 0.45,
    telemetryGain: 0.35,
    alertGain: 0.0,
    cinematicGain: 0.55,
    activeSources: ["DeepSpaceAmbience", "AvionicsHum"],
    fadeInDuration_s: 0.8,
    fadeOutDuration_s: 0.8,
  },
  {
    sceneId: 18,
    sceneKey: "SCENE_18_FINAL_REVEAL",
    ambienceGain: 0.30,
    spacecraftGain: 0.20,
    pulsarGain: 0.55,
    telemetryGain: 0.25,
    alertGain: 0.0,
    cinematicGain: 0.95,
    activeSources: ["DeepSpaceAmbience", "PulsarSonification", "CosmicClimax"],
    fadeInDuration_s: 1.5,
    fadeOutDuration_s: 2.0,
  },
];

export function getSceneAudioProfile(sceneId: number): SceneAudioProfile {
  const profile = SCENE_AUDIO_PROFILES.find((p) => p.sceneId === sceneId);
  return profile ?? SCENE_AUDIO_PROFILES[0];
}

export function getSceneAudioProfileByKey(sceneKey: string): SceneAudioProfile {
  const profile = SCENE_AUDIO_PROFILES.find((p) => p.sceneKey === sceneKey);
  return profile ?? SCENE_AUDIO_PROFILES[0];
}

export function lerpAudioProfiles(
  a: SceneAudioProfile,
  b: SceneAudioProfile,
  alpha: number
): SceneAudioProfile {
  const t = Math.max(0, Math.min(1, alpha));
  const lerp = (v1: number, v2: number) => v1 + (v2 - v1) * t;

  return {
    sceneId: t < 0.5 ? a.sceneId : b.sceneId,
    sceneKey: t < 0.5 ? a.sceneKey : b.sceneKey,
    ambienceGain: lerp(a.ambienceGain, b.ambienceGain),
    spacecraftGain: lerp(a.spacecraftGain, b.spacecraftGain),
    pulsarGain: lerp(a.pulsarGain, b.pulsarGain),
    telemetryGain: lerp(a.telemetryGain, b.telemetryGain),
    alertGain: lerp(a.alertGain, b.alertGain),
    cinematicGain: lerp(a.cinematicGain, b.cinematicGain),
    activeSources: t < 0.5 ? a.activeSources : b.activeSources,
    fadeInDuration_s: lerp(a.fadeInDuration_s, b.fadeInDuration_s),
    fadeOutDuration_s: lerp(a.fadeOutDuration_s, b.fadeOutDuration_s),
  };
}
